---
locales_present:
  - en_US.UTF-8

locales_language_packs_present:
  - language-pack-en
  - language-pack-en-base

locales_absent: []

locales_language_packs_absent: []

locales_default:
  lang: en_US.UTF-8
  lc_all: en_US.UTF-8
  lc_ctype: en_US.UTF-8
  language: en_US.UTF-8

essential_packages:
  - python3-pip
  - htop
  - tmux
  - vim
  - curl
  - wget
  - git
  - unzip
